### ISSUE TITLE
Printer share recursion

### ISSUE THREAD

**Issue by emperorcow** [CroweCybersecurity/shareenum#2]
Printer shares can, for some reason, cause an infinite loop depending on the recursion depth set causing an overflow of the buffer.

**Comment by jmmcatee** [comment]
I saw we just ignore recursion for printers, since we don't care about them and they should only be one deep.

**Comment by emperorcow** [comment]
I think this was never an issue but was mostly caused by setting the recursion flag and then having the buffer issues discussed before. I'm going to close it as I haven't had the issue for a while, we can re-open if need be.
