### ISSUE TITLE
Anonymous Enumeration false positives

### ISSUE THREAD

**Issue by jmmcatee** [CroweCybersecurity/shareenum#4]
When scanning a system with anonymous enumeration enabled, the system shows access that does not exit. For instance ADMIN$ shows up as WRITE permission for any valid user.

**Comment by emperorcow** [comment]
So I think this will be fixed in ad75de2ae7881150d9dd16dc21c6fd563b9cbcc1 on the 2.0 branch.  

@jmmcatee - Can you test this and let me know.
