### ISSUE TITLE
v2.0 Output Bug

### ISSUE THREAD

**Issue by jmmcatee** [CroweCybersecurity/shareenum#7]
For some of the output there are several lines that end up being Domain\Username, then two line breaks.

**Comment by emperorcow** [comment]
Any thoughts on if this is occuring at the end of hosts?  After a specific type?

**Comment by emperorcow** [comment]
I think this is because the output when we get an error is not being handled nicely.  The linked list has the right data, but smbresult_tocsv doesn't handle the error.  I will probably rewrite this to return a null and add some more logic instead of a lazy printf with functions.
